Repository pkgdeps/update-github-actions-permissions, pull requests merged in 2023-01, with the labels that each got.

#16 feat: support step-security/secure-workflows definitions
  .github/workflows/cron-update-third-party.yml
  .github/workflows/release.yml
  .github/workflows/remind-NPM-token.yml
  LICENSE
  LICENSE-MIT
  README.md
  package.json
  scripts/pull-secure-workflows.ts
  src/cli.ts
  src/index.ts
  src/types.ts
  test/index.test.ts
  test/snapshots/third-party-step-security/input.yml
  test/snapshots/third-party-step-security/output.yml
  third-party/secure-workflows.yml
  yarn.lock
Labels: Type: Feature, Status: Review Needed, Type: Breaking Change

#18 refactor: Moto to Pure ESM
  .mocharc.json
  package.json
  scripts/pull-secure-workflows.ts
  src/cli.ts
  src/index.ts
  src/types.validator.ts
  test/index.test.ts
  test/mergePermissions.test.ts
  test/tsconfig.json
  third-party/secure-workflows.yml
  tsconfig.json
  tsconfig.module.json
  yarn.lock
Labels: Type: Breaking Change

#20 fix: logging unknown actions names
  src/index.ts
Labels: Type: Bug
